name: Deploy Powershell project to Azure Function App - AyanM
on:
  # Trigger the workflow manually. But currently [Dec24] GitHub CICD isn't supported on Flex consumption.
  workflow_dispatch:

jobs:
  deploy:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1.5.2
        id: fa
        with:
          app-name: 'AyanM'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}